### ISSUE TITLE
Quick/Direct Downloads

### ISSUE THREAD

**Issue by psharma04** [thsconline/s#2]
Adding a method to download all papers from a particular subject at once would make using the site so much more efficient.

**Comment by thsconline** [comment]
Not really, it has been tried a long long time ago. I won't be putting this feature in, as I don't have a way to efficiency generate the ZIP files; and more importantly a means of deleting the ZIP files so that storage doesn't run out on Google Drive. 

It is possible to write a Powershell script to download all the files from a given webpage using Invoke-WebRequest. I will be looking to develop that at some point. But really its beyond the scope of this.
